version: '3'
services:
  # ---------------------------------------- DB
  # IMPORTANT NOTE: 
  # DO NOT USE ROOT as a user
  # DO NOT USE INSECURE password
  # Remove the mysql/ files in the volume
  db:
    restart: unless-stopped
    image: mysql:5.7
    environment:
      MYSQL_USER: ${WP_DB_USER} 
      MYSQL_PASSWORD: ${WP_DB_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${WP_DB_USER_PASSWORD}
      MYSQL_DATABASE: ${WP_DB_NAME}
    ports:
      - 3306:3306
    volumes: 
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./db/mysql:/var/lib/mysql
    networks: 
      - back
  # ---------------------------------------- WP
  # WP login:
  wp:
    depends_on: 
      - db
    restart: unless-stopped
    image: wordpress:latest
    ports:
      - 8081:80
    environment:
      WORDPRESS_DB_PASSWORD: ${WP_DB_USER_PASSWORD}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_TABLE_PREFIX: ${WP_DB_TABLE_PREFIX}
      WORDPRESS_DB_HOST: ${WP_DB_HOST}
      WORDPRESS_DEBUG: 1
        
    volumes: 
      - ./wp/wp-content:/var/www/html/wp-content
    networks: 
      - back
  # ---------------------------------------- PHPMYADMIN
  # PHP myadmin: 
  phpmyadmin:
      depends_on: 
        - db
      image: phpmyadmin/phpmyadmin
      ports:
        - 8082:80
      environment:
        MYSQL_ROOT_PASSWORD: ${WP_DB_USER_PASSWORD}
        PMA_HOST: db
      networks: 
        - back
networks:
  back: